// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TileService.proto

package TileService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RowId struct {
	RowId                string   `protobuf:"bytes,1,opt,name=rowId,proto3" json:"rowId,omitempty"`
	GetFullData          bool     `protobuf:"varint,2,opt,name=getFullData,proto3" json:"getFullData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowId) Reset()         { *m = RowId{} }
func (m *RowId) String() string { return proto.CompactTextString(m) }
func (*RowId) ProtoMessage()    {}
func (*RowId) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{0}
}

func (m *RowId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowId.Unmarshal(m, b)
}
func (m *RowId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowId.Marshal(b, m, deterministic)
}
func (m *RowId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowId.Merge(m, src)
}
func (m *RowId) XXX_Size() int {
	return xxx_messageInfo_RowId.Size(m)
}
func (m *RowId) XXX_DiscardUnknown() {
	xxx_messageInfo_RowId.DiscardUnknown(m)
}

var xxx_messageInfo_RowId proto.InternalMessageInfo

func (m *RowId) GetRowId() string {
	if m != nil {
		return m.RowId
	}
	return ""
}

func (m *RowId) GetGetFullData() bool {
	if m != nil {
		return m.GetFullData
	}
	return false
}

type RowContent struct {
	MovieTiles           []*MovieTile `protobuf:"bytes,1,rep,name=movieTiles,proto3" json:"movieTiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RowContent) Reset()         { *m = RowContent{} }
func (m *RowContent) String() string { return proto.CompactTextString(m) }
func (*RowContent) ProtoMessage()    {}
func (*RowContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{1}
}

func (m *RowContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowContent.Unmarshal(m, b)
}
func (m *RowContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowContent.Marshal(b, m, deterministic)
}
func (m *RowContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowContent.Merge(m, src)
}
func (m *RowContent) XXX_Size() int {
	return xxx_messageInfo_RowContent.Size(m)
}
func (m *RowContent) XXX_DiscardUnknown() {
	xxx_messageInfo_RowContent.DiscardUnknown(m)
}

var xxx_messageInfo_RowContent proto.InternalMessageInfo

func (m *RowContent) GetMovieTiles() []*MovieTile {
	if m != nil {
		return m.MovieTiles
	}
	return nil
}

type MovieTile struct {
	RefId                string    `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Posters              *POSTERS  `protobuf:"bytes,2,opt,name=posters,proto3" json:"posters,omitempty"`
	Content              *CONTENT  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata             *METADATA `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MovieTile) Reset()         { *m = MovieTile{} }
func (m *MovieTile) String() string { return proto.CompactTextString(m) }
func (*MovieTile) ProtoMessage()    {}
func (*MovieTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{2}
}

func (m *MovieTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieTile.Unmarshal(m, b)
}
func (m *MovieTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieTile.Marshal(b, m, deterministic)
}
func (m *MovieTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieTile.Merge(m, src)
}
func (m *MovieTile) XXX_Size() int {
	return xxx_messageInfo_MovieTile.Size(m)
}
func (m *MovieTile) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieTile.DiscardUnknown(m)
}

var xxx_messageInfo_MovieTile proto.InternalMessageInfo

func (m *MovieTile) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *MovieTile) GetPosters() *POSTERS {
	if m != nil {
		return m.Posters
	}
	return nil
}

func (m *MovieTile) GetContent() *CONTENT {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MovieTile) GetMetadata() *METADATA {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type POSTERS struct {
	Landscape            []string `protobuf:"bytes,1,rep,name=landscape,proto3" json:"landscape,omitempty"`
	Portrait             []string `protobuf:"bytes,2,rep,name=portrait,proto3" json:"portrait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTERS) Reset()         { *m = POSTERS{} }
func (m *POSTERS) String() string { return proto.CompactTextString(m) }
func (*POSTERS) ProtoMessage()    {}
func (*POSTERS) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{3}
}

func (m *POSTERS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTERS.Unmarshal(m, b)
}
func (m *POSTERS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTERS.Marshal(b, m, deterministic)
}
func (m *POSTERS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTERS.Merge(m, src)
}
func (m *POSTERS) XXX_Size() int {
	return xxx_messageInfo_POSTERS.Size(m)
}
func (m *POSTERS) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTERS.DiscardUnknown(m)
}

var xxx_messageInfo_POSTERS proto.InternalMessageInfo

func (m *POSTERS) GetLandscape() []string {
	if m != nil {
		return m.Landscape
	}
	return nil
}

func (m *POSTERS) GetPortrait() []string {
	if m != nil {
		return m.Portrait
	}
	return nil
}

type METADATA struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *METADATA) Reset()         { *m = METADATA{} }
func (m *METADATA) String() string { return proto.CompactTextString(m) }
func (*METADATA) ProtoMessage()    {}
func (*METADATA) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{4}
}

func (m *METADATA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_METADATA.Unmarshal(m, b)
}
func (m *METADATA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_METADATA.Marshal(b, m, deterministic)
}
func (m *METADATA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_METADATA.Merge(m, src)
}
func (m *METADATA) XXX_Size() int {
	return xxx_messageInfo_METADATA.Size(m)
}
func (m *METADATA) XXX_DiscardUnknown() {
	xxx_messageInfo_METADATA.DiscardUnknown(m)
}

var xxx_messageInfo_METADATA proto.InternalMessageInfo

func (m *METADATA) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CONTENT struct {
	DetailPage           bool     `protobuf:"varint,1,opt,name=detailPage,proto3" json:"detailPage,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Target               []string `protobuf:"bytes,3,rep,name=target,proto3" json:"target,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PlaystoreUrl         string   `protobuf:"bytes,5,opt,name=playstoreUrl,proto3" json:"playstoreUrl,omitempty"`
	UseAlternate         bool     `protobuf:"varint,6,opt,name=useAlternate,proto3" json:"useAlternate,omitempty"`
	AlternateUrl         string   `protobuf:"bytes,7,opt,name=alternateUrl,proto3" json:"alternateUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CONTENT) Reset()         { *m = CONTENT{} }
func (m *CONTENT) String() string { return proto.CompactTextString(m) }
func (*CONTENT) ProtoMessage()    {}
func (*CONTENT) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{5}
}

func (m *CONTENT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CONTENT.Unmarshal(m, b)
}
func (m *CONTENT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CONTENT.Marshal(b, m, deterministic)
}
func (m *CONTENT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CONTENT.Merge(m, src)
}
func (m *CONTENT) XXX_Size() int {
	return xxx_messageInfo_CONTENT.Size(m)
}
func (m *CONTENT) XXX_DiscardUnknown() {
	xxx_messageInfo_CONTENT.DiscardUnknown(m)
}

var xxx_messageInfo_CONTENT proto.InternalMessageInfo

func (m *CONTENT) GetDetailPage() bool {
	if m != nil {
		return m.DetailPage
	}
	return false
}

func (m *CONTENT) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *CONTENT) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CONTENT) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CONTENT) GetPlaystoreUrl() string {
	if m != nil {
		return m.PlaystoreUrl
	}
	return ""
}

func (m *CONTENT) GetUseAlternate() bool {
	if m != nil {
		return m.UseAlternate
	}
	return false
}

func (m *CONTENT) GetAlternateUrl() string {
	if m != nil {
		return m.AlternateUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*RowId)(nil), "TileService.RowId")
	proto.RegisterType((*RowContent)(nil), "TileService.RowContent")
	proto.RegisterType((*MovieTile)(nil), "TileService.MovieTile")
	proto.RegisterType((*POSTERS)(nil), "TileService.POSTERS")
	proto.RegisterType((*METADATA)(nil), "TileService.METADATA")
	proto.RegisterType((*CONTENT)(nil), "TileService.CONTENT")
}

func init() { proto.RegisterFile("TileService.proto", fileDescriptor_28928c4b0d64237b) }

var fileDescriptor_28928c4b0d64237b = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x69, 0x13, 0xdb, 0x13, 0x38, 0x30, 0x6a, 0xab, 0x55, 0x85, 0x90, 0xb5, 0xa7, 0x9c,
	0x22, 0x08, 0x12, 0xd7, 0x2a, 0x4a, 0x02, 0xea, 0x81, 0xb4, 0xda, 0x98, 0x33, 0x5a, 0xe2, 0x69,
	0x64, 0xb1, 0xcd, 0x5a, 0xeb, 0x69, 0xab, 0x7e, 0x18, 0x5f, 0xc3, 0xcf, 0xa0, 0xdd, 0xc4, 0xae,
	0x2d, 0xc1, 0x6d, 0xdf, 0x9b, 0xe7, 0xb7, 0x6f, 0xbc, 0x0f, 0xde, 0xe6, 0xa5, 0xa1, 0x0d, 0xb9,
	0xc7, 0x72, 0x4b, 0xd3, 0xca, 0x59, 0xb6, 0x38, 0xee, 0x50, 0xf2, 0x0a, 0x86, 0xca, 0x3e, 0x5d,
	0x17, 0x78, 0x06, 0x43, 0xe7, 0x0f, 0x22, 0xca, 0xa2, 0x49, 0xaa, 0x0e, 0x00, 0x33, 0x18, 0xef,
	0x88, 0xbf, 0x3c, 0x18, 0xb3, 0xd4, 0xac, 0xc5, 0x20, 0x8b, 0x26, 0x89, 0xea, 0x52, 0x72, 0x09,
	0xa0, 0xec, 0xd3, 0xc2, 0xee, 0x99, 0xf6, 0x8c, 0x9f, 0x01, 0xee, 0xed, 0x63, 0x49, 0xfe, 0x8a,
	0x5a, 0x44, 0xd9, 0xc9, 0x64, 0x3c, 0xbb, 0x98, 0x76, 0x33, 0x7c, 0x6b, 0xc6, 0xaa, 0xa3, 0x94,
	0xbf, 0x23, 0x48, 0xdb, 0x09, 0x9e, 0xc3, 0xc8, 0xd1, 0xdd, 0x8f, 0xf2, 0x25, 0x0c, 0xdd, 0x5d,
	0x17, 0x38, 0x85, 0xb8, 0xb2, 0x35, 0x93, 0xab, 0x43, 0x90, 0xf1, 0xec, 0xac, 0xe7, 0x7c, 0x7b,
	0xb3, 0xc9, 0x57, 0x6a, 0xa3, 0x1a, 0x91, 0xd7, 0x6f, 0x0f, 0xb9, 0xc4, 0xc9, 0x3f, 0xf4, 0x8b,
	0x9b, 0x75, 0xbe, 0x5a, 0xe7, 0xaa, 0x11, 0xe1, 0x47, 0x48, 0xee, 0x89, 0x75, 0xe1, 0x37, 0x3d,
	0x0d, 0x1f, 0x9c, 0xf7, 0xa3, 0xaf, 0xf2, 0xf9, 0x72, 0x9e, 0xcf, 0x55, 0x2b, 0x93, 0x0b, 0x88,
	0x8f, 0xd7, 0xe2, 0x3b, 0x48, 0x8d, 0xde, 0x17, 0xf5, 0x56, 0x57, 0x14, 0x36, 0x4f, 0xd5, 0x0b,
	0x81, 0x97, 0x90, 0x54, 0xd6, 0xb1, 0xd3, 0x25, 0x8b, 0x41, 0x18, 0xb6, 0x58, 0x66, 0x90, 0x34,
	0xd6, 0xfe, 0x19, 0xb8, 0x64, 0x43, 0xcd, 0xe6, 0x01, 0xc8, 0x3f, 0x11, 0xc4, 0xc7, 0xb8, 0xf8,
	0x1e, 0xa0, 0x20, 0xd6, 0xa5, 0xb9, 0xd5, 0xbb, 0x83, 0x2c, 0x51, 0x1d, 0x06, 0x05, 0xc4, 0x95,
	0xde, 0xfe, 0xf2, 0xc3, 0x41, 0xf0, 0x68, 0x20, 0x5e, 0xc0, 0x88, 0xb5, 0xdb, 0x91, 0xff, 0x1d,
	0x3e, 0xc1, 0x11, 0x21, 0xc2, 0x29, 0x3f, 0x57, 0x14, 0x76, 0x4e, 0x55, 0x38, 0xa3, 0x84, 0xd7,
	0x95, 0xd1, 0xcf, 0x35, 0x5b, 0x47, 0xdf, 0x9d, 0x11, 0xc3, 0x30, 0xeb, 0x71, 0x5e, 0xf3, 0x50,
	0xd3, 0xdc, 0x30, 0xb9, 0xbd, 0x66, 0x12, 0xa3, 0x90, 0xa5, 0xc7, 0x79, 0x8d, 0x6e, 0x80, 0xf7,
	0x89, 0x0f, 0x3e, 0x5d, 0x6e, 0xb6, 0x86, 0x6e, 0x25, 0xf1, 0x0a, 0xde, 0x7c, 0x25, 0x6e, 0xdb,
	0x50, 0x23, 0xf6, 0x5e, 0x21, 0xd4, 0xf5, 0xf2, 0x3f, 0xa5, 0x92, 0xaf, 0x3e, 0x44, 0x3f, 0x47,
	0xa1, 0xe7, 0x9f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xf0, 0x55, 0x1b, 0xfc, 0x02, 0x00,
	0x00,
}
