// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TileService.proto

package TileService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitializingEngineRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializingEngineRequest) Reset()         { *m = InitializingEngineRequest{} }
func (m *InitializingEngineRequest) String() string { return proto.CompactTextString(m) }
func (*InitializingEngineRequest) ProtoMessage()    {}
func (*InitializingEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{0}
}

func (m *InitializingEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializingEngineRequest.Unmarshal(m, b)
}
func (m *InitializingEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializingEngineRequest.Marshal(b, m, deterministic)
}
func (m *InitializingEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializingEngineRequest.Merge(m, src)
}
func (m *InitializingEngineRequest) XXX_Size() int {
	return xxx_messageInfo_InitializingEngineRequest.Size(m)
}
func (m *InitializingEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializingEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializingEngineRequest proto.InternalMessageInfo

func (m *InitializingEngineRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type InitializingEngineResponse struct {
	IsDone               bool     `protobuf:"varint,1,opt,name=isDone,proto3" json:"isDone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializingEngineResponse) Reset()         { *m = InitializingEngineResponse{} }
func (m *InitializingEngineResponse) String() string { return proto.CompactTextString(m) }
func (*InitializingEngineResponse) ProtoMessage()    {}
func (*InitializingEngineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{1}
}

func (m *InitializingEngineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializingEngineResponse.Unmarshal(m, b)
}
func (m *InitializingEngineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializingEngineResponse.Marshal(b, m, deterministic)
}
func (m *InitializingEngineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializingEngineResponse.Merge(m, src)
}
func (m *InitializingEngineResponse) XXX_Size() int {
	return xxx_messageInfo_InitializingEngineResponse.Size(m)
}
func (m *InitializingEngineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializingEngineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializingEngineResponse proto.InternalMessageInfo

func (m *InitializingEngineResponse) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

type RowId struct {
	RowId                string   `protobuf:"bytes,1,opt,name=rowId,proto3" json:"rowId,omitempty"`
	GetFullData          bool     `protobuf:"varint,2,opt,name=getFullData,proto3" json:"getFullData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowId) Reset()         { *m = RowId{} }
func (m *RowId) String() string { return proto.CompactTextString(m) }
func (*RowId) ProtoMessage()    {}
func (*RowId) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{2}
}

func (m *RowId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowId.Unmarshal(m, b)
}
func (m *RowId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowId.Marshal(b, m, deterministic)
}
func (m *RowId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowId.Merge(m, src)
}
func (m *RowId) XXX_Size() int {
	return xxx_messageInfo_RowId.Size(m)
}
func (m *RowId) XXX_DiscardUnknown() {
	xxx_messageInfo_RowId.DiscardUnknown(m)
}

var xxx_messageInfo_RowId proto.InternalMessageInfo

func (m *RowId) GetRowId() string {
	if m != nil {
		return m.RowId
	}
	return ""
}

func (m *RowId) GetGetFullData() bool {
	if m != nil {
		return m.GetFullData
	}
	return false
}

type RowContent struct {
	MovieTiles           []*MovieTile `protobuf:"bytes,1,rep,name=movieTiles,proto3" json:"movieTiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RowContent) Reset()         { *m = RowContent{} }
func (m *RowContent) String() string { return proto.CompactTextString(m) }
func (*RowContent) ProtoMessage()    {}
func (*RowContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{3}
}

func (m *RowContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowContent.Unmarshal(m, b)
}
func (m *RowContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowContent.Marshal(b, m, deterministic)
}
func (m *RowContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowContent.Merge(m, src)
}
func (m *RowContent) XXX_Size() int {
	return xxx_messageInfo_RowContent.Size(m)
}
func (m *RowContent) XXX_DiscardUnknown() {
	xxx_messageInfo_RowContent.DiscardUnknown(m)
}

var xxx_messageInfo_RowContent proto.InternalMessageInfo

func (m *RowContent) GetMovieTiles() []*MovieTile {
	if m != nil {
		return m.MovieTiles
	}
	return nil
}

type GetRowsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Vendor               string   `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRowsRequest) Reset()         { *m = GetRowsRequest{} }
func (m *GetRowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRowsRequest) ProtoMessage()    {}
func (*GetRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{4}
}

func (m *GetRowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowsRequest.Unmarshal(m, b)
}
func (m *GetRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowsRequest.Marshal(b, m, deterministic)
}
func (m *GetRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowsRequest.Merge(m, src)
}
func (m *GetRowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRowsRequest.Size(m)
}
func (m *GetRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowsRequest proto.InternalMessageInfo

func (m *GetRowsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetRowsRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *GetRowsRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type GetRowsResponse struct {
	RowSpec              []*RowSpec `protobuf:"bytes,1,rep,name=rowSpec,proto3" json:"rowSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetRowsResponse) Reset()         { *m = GetRowsResponse{} }
func (m *GetRowsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRowsResponse) ProtoMessage()    {}
func (*GetRowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{5}
}

func (m *GetRowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowsResponse.Unmarshal(m, b)
}
func (m *GetRowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowsResponse.Marshal(b, m, deterministic)
}
func (m *GetRowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowsResponse.Merge(m, src)
}
func (m *GetRowsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRowsResponse.Size(m)
}
func (m *GetRowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowsResponse proto.InternalMessageInfo

func (m *GetRowsResponse) GetRowSpec() []*RowSpec {
	if m != nil {
		return m.RowSpec
	}
	return nil
}

type RowSpec struct {
	RowName              string   `protobuf:"bytes,1,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowId                string   `protobuf:"bytes,2,opt,name=rowId,proto3" json:"rowId,omitempty"`
	RowShape             string   `protobuf:"bytes,3,opt,name=rowShape,proto3" json:"rowShape,omitempty"`
	RowPosition          int32    `protobuf:"varint,4,opt,name=rowPosition,proto3" json:"rowPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowSpec) Reset()         { *m = RowSpec{} }
func (m *RowSpec) String() string { return proto.CompactTextString(m) }
func (*RowSpec) ProtoMessage()    {}
func (*RowSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{6}
}

func (m *RowSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowSpec.Unmarshal(m, b)
}
func (m *RowSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowSpec.Marshal(b, m, deterministic)
}
func (m *RowSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowSpec.Merge(m, src)
}
func (m *RowSpec) XXX_Size() int {
	return xxx_messageInfo_RowSpec.Size(m)
}
func (m *RowSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_RowSpec.DiscardUnknown(m)
}

var xxx_messageInfo_RowSpec proto.InternalMessageInfo

func (m *RowSpec) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *RowSpec) GetRowId() string {
	if m != nil {
		return m.RowId
	}
	return ""
}

func (m *RowSpec) GetRowShape() string {
	if m != nil {
		return m.RowShape
	}
	return ""
}

func (m *RowSpec) GetRowPosition() int32 {
	if m != nil {
		return m.RowPosition
	}
	return 0
}

type MovieTile struct {
	RefId                string    `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Posters              *POSTERS  `protobuf:"bytes,2,opt,name=posters,proto3" json:"posters,omitempty"`
	Content              *CONTENT  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata             *METADATA `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MovieTile) Reset()         { *m = MovieTile{} }
func (m *MovieTile) String() string { return proto.CompactTextString(m) }
func (*MovieTile) ProtoMessage()    {}
func (*MovieTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{7}
}

func (m *MovieTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieTile.Unmarshal(m, b)
}
func (m *MovieTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieTile.Marshal(b, m, deterministic)
}
func (m *MovieTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieTile.Merge(m, src)
}
func (m *MovieTile) XXX_Size() int {
	return xxx_messageInfo_MovieTile.Size(m)
}
func (m *MovieTile) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieTile.DiscardUnknown(m)
}

var xxx_messageInfo_MovieTile proto.InternalMessageInfo

func (m *MovieTile) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *MovieTile) GetPosters() *POSTERS {
	if m != nil {
		return m.Posters
	}
	return nil
}

func (m *MovieTile) GetContent() *CONTENT {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MovieTile) GetMetadata() *METADATA {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type POSTERS struct {
	Landscape            []string `protobuf:"bytes,1,rep,name=landscape,proto3" json:"landscape,omitempty"`
	Portrait             []string `protobuf:"bytes,2,rep,name=portrait,proto3" json:"portrait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTERS) Reset()         { *m = POSTERS{} }
func (m *POSTERS) String() string { return proto.CompactTextString(m) }
func (*POSTERS) ProtoMessage()    {}
func (*POSTERS) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{8}
}

func (m *POSTERS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTERS.Unmarshal(m, b)
}
func (m *POSTERS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTERS.Marshal(b, m, deterministic)
}
func (m *POSTERS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTERS.Merge(m, src)
}
func (m *POSTERS) XXX_Size() int {
	return xxx_messageInfo_POSTERS.Size(m)
}
func (m *POSTERS) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTERS.DiscardUnknown(m)
}

var xxx_messageInfo_POSTERS proto.InternalMessageInfo

func (m *POSTERS) GetLandscape() []string {
	if m != nil {
		return m.Landscape
	}
	return nil
}

func (m *POSTERS) GetPortrait() []string {
	if m != nil {
		return m.Portrait
	}
	return nil
}

type METADATA struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *METADATA) Reset()         { *m = METADATA{} }
func (m *METADATA) String() string { return proto.CompactTextString(m) }
func (*METADATA) ProtoMessage()    {}
func (*METADATA) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{9}
}

func (m *METADATA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_METADATA.Unmarshal(m, b)
}
func (m *METADATA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_METADATA.Marshal(b, m, deterministic)
}
func (m *METADATA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_METADATA.Merge(m, src)
}
func (m *METADATA) XXX_Size() int {
	return xxx_messageInfo_METADATA.Size(m)
}
func (m *METADATA) XXX_DiscardUnknown() {
	xxx_messageInfo_METADATA.DiscardUnknown(m)
}

var xxx_messageInfo_METADATA proto.InternalMessageInfo

func (m *METADATA) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CONTENT struct {
	DetailPage           bool     `protobuf:"varint,1,opt,name=detailPage,proto3" json:"detailPage,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Target               []string `protobuf:"bytes,3,rep,name=target,proto3" json:"target,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CONTENT) Reset()         { *m = CONTENT{} }
func (m *CONTENT) String() string { return proto.CompactTextString(m) }
func (*CONTENT) ProtoMessage()    {}
func (*CONTENT) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{10}
}

func (m *CONTENT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CONTENT.Unmarshal(m, b)
}
func (m *CONTENT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CONTENT.Marshal(b, m, deterministic)
}
func (m *CONTENT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CONTENT.Merge(m, src)
}
func (m *CONTENT) XXX_Size() int {
	return xxx_messageInfo_CONTENT.Size(m)
}
func (m *CONTENT) XXX_DiscardUnknown() {
	xxx_messageInfo_CONTENT.DiscardUnknown(m)
}

var xxx_messageInfo_CONTENT proto.InternalMessageInfo

func (m *CONTENT) GetDetailPage() bool {
	if m != nil {
		return m.DetailPage
	}
	return false
}

func (m *CONTENT) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *CONTENT) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CONTENT) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*InitializingEngineRequest)(nil), "TileService.InitializingEngineRequest")
	proto.RegisterType((*InitializingEngineResponse)(nil), "TileService.InitializingEngineResponse")
	proto.RegisterType((*RowId)(nil), "TileService.RowId")
	proto.RegisterType((*RowContent)(nil), "TileService.RowContent")
	proto.RegisterType((*GetRowsRequest)(nil), "TileService.GetRowsRequest")
	proto.RegisterType((*GetRowsResponse)(nil), "TileService.GetRowsResponse")
	proto.RegisterType((*RowSpec)(nil), "TileService.RowSpec")
	proto.RegisterType((*MovieTile)(nil), "TileService.MovieTile")
	proto.RegisterType((*POSTERS)(nil), "TileService.POSTERS")
	proto.RegisterType((*METADATA)(nil), "TileService.METADATA")
	proto.RegisterType((*CONTENT)(nil), "TileService.CONTENT")
}

func init() { proto.RegisterFile("TileService.proto", fileDescriptor_28928c4b0d64237b) }

var fileDescriptor_28928c4b0d64237b = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xd4, 0x3e,
	0x10, 0x6d, 0xfa, 0x67, 0xb3, 0x99, 0xea, 0xf7, 0x43, 0x58, 0x6d, 0x15, 0x16, 0x84, 0x56, 0x3e,
	0x40, 0x4f, 0x15, 0x94, 0x3f, 0xd7, 0xb2, 0xea, 0x2e, 0xd5, 0x1e, 0x68, 0x2b, 0x6f, 0xc4, 0x15,
	0xb9, 0x9b, 0x69, 0xb0, 0x9a, 0xda, 0xc1, 0x76, 0x37, 0x2a, 0xdf, 0x8b, 0x0f, 0xc7, 0x0d, 0x39,
	0x71, 0xb2, 0xd9, 0xa5, 0x15, 0xb7, 0xbc, 0xf1, 0x1b, 0xe7, 0xcd, 0x9b, 0x19, 0xc3, 0xd3, 0x44,
	0xe4, 0x38, 0x43, 0xbd, 0x10, 0x73, 0x3c, 0x2a, 0xb4, 0xb2, 0x8a, 0xec, 0x76, 0x42, 0xf4, 0x03,
	0x3c, 0x9b, 0x4a, 0x61, 0x05, 0xcf, 0xc5, 0x4f, 0x21, 0xb3, 0x89, 0xcc, 0x84, 0x44, 0x86, 0x3f,
	0xee, 0xd0, 0x58, 0x12, 0x43, 0x78, 0x83, 0xf7, 0xa5, 0xd2, 0x69, 0x1c, 0x0c, 0x83, 0xc3, 0x88,
	0x35, 0x90, 0xbe, 0x87, 0xc1, 0x43, 0x69, 0xa6, 0x50, 0xd2, 0x20, 0x39, 0x80, 0x9e, 0x30, 0x63,
	0x25, 0xb1, 0x4a, 0xeb, 0x33, 0x8f, 0xe8, 0x09, 0xec, 0x30, 0x55, 0x4e, 0x53, 0xb2, 0x07, 0x3b,
	0xda, 0x7d, 0xf8, 0x6b, 0x6b, 0x40, 0x86, 0xb0, 0x9b, 0xa1, 0xfd, 0x7c, 0x97, 0xe7, 0x63, 0x6e,
	0x79, 0xbc, 0x59, 0xe5, 0x76, 0x43, 0x74, 0x0c, 0xc0, 0x54, 0x79, 0xaa, 0xa4, 0x45, 0x69, 0xc9,
	0x47, 0x80, 0x5b, 0xb5, 0x10, 0xe8, 0xea, 0x31, 0x71, 0x30, 0xdc, 0x3a, 0xdc, 0x3d, 0x3e, 0x38,
	0xea, 0x16, 0xfc, 0xa5, 0x39, 0x66, 0x1d, 0x26, 0xfd, 0x0a, 0xff, 0x9f, 0xa1, 0x65, 0xaa, 0x34,
	0x4d, 0xa1, 0x07, 0xd0, 0xbb, 0x33, 0xa8, 0x5b, 0x41, 0x1e, 0xb9, 0xf8, 0x02, 0x65, 0xaa, 0x74,
	0x25, 0x26, 0x62, 0x1e, 0x39, 0xfd, 0x57, 0x9a, 0xcb, 0x34, 0xde, 0xaa, 0xf5, 0x57, 0x80, 0x8e,
	0xe0, 0x49, 0x7b, 0xaf, 0x77, 0xe2, 0x08, 0x42, 0xad, 0xca, 0x59, 0x81, 0x73, 0xaf, 0x6f, 0x6f,
	0x45, 0x1f, 0xab, 0xcf, 0x58, 0x43, 0xa2, 0x25, 0x84, 0x3e, 0xe6, 0xcc, 0xd7, 0xaa, 0x3c, 0xe7,
	0xb7, 0xd8, 0x98, 0xef, 0xe1, 0xd2, 0xbd, 0xcd, 0xae, 0x7b, 0x03, 0xe8, 0xbb, 0x5b, 0xbe, 0xf3,
	0x02, 0xbd, 0xac, 0x16, 0x3b, 0x67, 0xb5, 0x2a, 0x2f, 0x95, 0x11, 0x56, 0x28, 0x19, 0x6f, 0x0f,
	0x83, 0xc3, 0x1d, 0xd6, 0x0d, 0xd1, 0x5f, 0x01, 0x44, 0xad, 0x5b, 0x64, 0x1f, 0x7a, 0x1a, 0xaf,
	0xbf, 0x89, 0x65, 0x83, 0xf0, 0x7a, 0x9a, 0xba, 0x6a, 0x0a, 0x65, 0x2c, 0x6a, 0x53, 0xfd, 0x7a,
	0xbd, 0x9a, 0xcb, 0x8b, 0x59, 0x32, 0x61, 0x33, 0xd6, 0x90, 0x1c, 0x7f, 0x5e, 0xf7, 0xaa, 0x52,
	0xb4, 0xce, 0x3f, 0xbd, 0x38, 0x4f, 0x26, 0xe7, 0x09, 0x6b, 0x48, 0xe4, 0x2d, 0xf4, 0x6f, 0xd1,
	0xf2, 0xd4, 0x75, 0x7f, 0xbb, 0x4a, 0xd8, 0x5f, 0x6d, 0xe7, 0x24, 0x19, 0x8d, 0x47, 0xc9, 0x88,
	0xb5, 0x34, 0x7a, 0x0a, 0xa1, 0xff, 0x2d, 0x79, 0x01, 0x51, 0xce, 0x65, 0x6a, 0xe6, 0xce, 0x01,
	0xe7, 0x76, 0xc4, 0x96, 0x01, 0x67, 0x4f, 0xa1, 0xb4, 0xd5, 0x5c, 0xd8, 0x78, 0xb3, 0x3a, 0x6c,
	0x31, 0x1d, 0x42, 0xbf, 0xb9, 0xda, 0x99, 0x6b, 0x85, 0xcd, 0x1b, 0xd3, 0x6b, 0x40, 0x15, 0x84,
	0x5e, 0x2d, 0x79, 0x09, 0x90, 0xa2, 0xe5, 0x22, 0xbf, 0xe4, 0x59, 0x33, 0xe0, 0x9d, 0x88, 0xeb,
	0x5b, 0xc1, 0xe7, 0x37, 0xee, 0xb0, 0xee, 0x4f, 0x03, 0xdd, 0x34, 0x59, 0xae, 0x33, 0x74, 0x6e,
	0x38, 0x01, 0x1e, 0x11, 0x02, 0xdb, 0xf6, 0xbe, 0xc0, 0xaa, 0xe4, 0x88, 0x55, 0xdf, 0xc7, 0xbf,
	0x03, 0xe8, 0xee, 0x29, 0x39, 0x81, 0xff, 0xce, 0xd0, 0xb6, 0x1d, 0x32, 0x84, 0xac, 0x0f, 0xd2,
	0x34, 0x1d, 0x3c, 0x32, 0xfc, 0x74, 0xe3, 0x4d, 0x40, 0x32, 0x20, 0x7f, 0x6f, 0x2c, 0x79, 0xb5,
	0x92, 0xf1, 0xe8, 0x4b, 0x30, 0x78, 0xfd, 0x4f, 0x5e, 0x3d, 0xf0, 0x74, 0x83, 0x7c, 0x82, 0xd0,
	0x6f, 0x01, 0x79, 0xbe, 0x92, 0xb5, 0xba, 0x73, 0x83, 0x07, 0x37, 0xc1, 0x49, 0xbd, 0xea, 0x55,
	0xef, 0xd4, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x4b, 0xe9, 0xe0, 0xbc, 0x04, 0x00,
	0x00,
}
